name: ShellCheck CI
run-name: ShellCheck CI triggered from @${{ github.actor }} of ${{ github.head_ref }}

on:
  # NOTE: Disabled for PR/merge_group/push; manual only during repo development.
  workflow_dispatch:

jobs:
  shellcheck:
    name: Run ShellCheck
    runs-on: ubuntu-8
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          ignore_paths: >-
            ./fastcache/**
            ./contracts/**
            ./safe-smart-account/**
            ./go-ethereum/**
            ./nitro-testnode/**
            ./brotli/**
            ./arbitrator/**
